//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_New
    {
        public int User_id { get; set; }
        public string First_Name { get; set; }
        public string Last_name { get; set; }
        public int Employee_id { get; set; }
    }
}
